# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7afbc8b3d5b88c0c0431279d085c632662212514e7db37cf80007f87fb9a5eba9aa7fd2e9e76d31e75056ed26006075ab2d43d3c4ca177636244e3f2b44aee85

test:
  secret_key_base: 0c03d032f35780c20759b19c06948d4329c068ee5daacea35fb07934bc7a3a53e680c92c737e3210af84dc2288af56a84acd232962ca6038e4721e29dc95e423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
